site :opscode
cookbook 'hostname'
cookbook 'selinux'
cookbook 'yum'
cookbook 'openssh'
cookbook 'ntp'
cookbook 'sysctl'
cookbook 'users'
cookbook 'nginx', '1.4.0'
cookbook 'runit', '1.0.0'
cookbook 'chef-solo-search', git:'https://github.com/edelight/chef-solo-search.git'
cookbook 'daemontools', git:'https://github.com/seiji/daemontools.git'
cookbook 'git'
cookbook 'redis',         git: 'https://github.com/brianbianco/redisio.git'
cookbook 'mongodb',       :path => 'site-cookbooks/mongodb'
cookbook 'mysql',         :path => 'site-cookbooks/mysql'
cookbook 'nodejs',        git: 'https://github.com/hectcastro/chef-nodejs.git'
cookbook 'znc',           :path => 'site-cookbooks/znc'
