site :opscode
cookbook 'hostname'
cookbook 'selinux'
cookbook 'yum'
cookbook 'openssh'
cookbook 'ntp'
cookbook 'sysctl'
cookbook 'users'
cookbook 'nginx', '1.4.0'
cookbook 'runit', '1.0.0'
cookbook 'chef-solo-search', git:'https://github.com/edelight/chef-solo-search.git'
cookbook 'git'
cookbook 'redis'

cookbook 'mongodb',       :path => 'site-cookbooks/mongodb'
cookbook 'znc',           :path => 'site-cookbooks/znc'
